### ISSUE TITLE
[Feature Request] Add word frequency lists

### ISSUE THREAD

**Issue by GrimPixel** [max-niederman/ttyper#52] opened 2022-06-09 20:52 UTC
There is a guy who gathered the lists:
https://github.com/frekwencja/most-common-words-multilingual

**Comment by GrimPixel** [comment] 2022-06-09 21:06
Looks like the data is not released for free. Now I doubt if that is legal.

**Comment by GrimPixel** [comment] 2022-06-10 08:27
I saw the page. They allow the redistribution of their free data.
https://www.wordfrequency.info/samples.asp

**Comment by max-niederman** [comment] 2022-06-19 06:05
This is a considered feature for v1.0.

**Comment by max-niederman** [comment] 2023-02-10 01:47
Duplicate of #2.

**Closed** 2023-02-10 01:47 UTC
Labels: enhancement
